### ISSUE TITLE
request for contact info

### ISSUE THREAD

**Issue by anggadarkprince** [anggadarkprince/web-collaboration-design#1]
@sketchproject please edit contact info on footer

**Comment by sketchproject** [comment]
ok tonight the website ready to go..

**Comment by anggadarkprince** [comment]
thanks for your hardwork..

**Comment by sketchproject** [comment]
hmm i think, there is problem with markup, i'm ready for saturday..

**Comment by anggadarkprince** [comment]
ok,,, we will wait..
